apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.69.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: deployment
    config:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
      exporters:
        logging:
        loki:
          endpoint: http://loki:3100/loki/api/v1/push
        tempo:
          endpoint: tempo:4317
        prometheus:
          endpoint: prometheus-server
      service:
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [loki]
          traces:
            receivers: [otlp]
            exporters: [tempo]
          metrics:
            receivers: [otlp]
            exporters: [prometheus]
